#!/usr/bin/python3
import sys
import socket

data = " ".join(sys.argv[1:])
port = int(sys.argv[1])
label = sys.argv[2]
symbol = sys.argv[3]
action = sys.argv[4]

msg = " ".join([label,symbol, action])
print(msg)

clientSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM);
clientSocket.connect(("127.0.0.1",port));
clientSocket.send(msg.encode());
resp = clientSocket.recv(1024);
print(resp.decode());
