#!/usr/bin/python3
import os
import sys
import socket

data = " ".join(sys.argv[1:])
clientSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM);
clientSocket.connect(("127.0.0.1",3003));
clientSocket.send(data.encode());
dataFromServer = clientSocket.recv(1024);
print(dataFromServer.decode());
